In [10]:
import tensorflow as tf
print('TensorFlow Version:', tf.__version__)

TensorFlow Version: 2.16.1


In [11]:
mnist = tf.keras.datasets.mnist

In [15]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train /255.0, x_test /255.0

In [16]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28, 28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

/home/pratiyushp/anaconda3/envs/My_Workspace/lib/python3.11/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [17]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6093569 , -0.05038551, -0.14253627,  0.1668219 ,  0.08535983,
        -0.48308408,  0.2840574 ,  0.22134303, -0.37792242, -1.0021528 ]],
      dtype=float32)

In [18]:
tf.nn.softmax(predictions).numpy()

array([[0.06124213, 0.10710468, 0.09767601, 0.13308847, 0.12267666,
        0.06948481, 0.14964257, 0.14054605, 0.07718999, 0.04134864]],
      dtype=float32)

In [19]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
loss_fn(y_train[:1], predictions).numpy()

2.666647

In [21]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [23]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8602 - loss: 0.4826
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9562 - loss: 0.1523
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9662 - loss: 0.1115
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9721 - loss: 0.0892
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9770 - loss: 0.0745


In [24]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 2ms/step - accuracy: 0.9762 - loss: 0.0742


[0.07420622557401657, 0.9761999845504761]

In [25]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [26]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.9707672e-09, 4.9891207e-09, 1.0207302e-05, 5.3718755e-05,
        6.9263838e-11, 5.9098657e-08, 1.1933689e-13, 9.9993384e-01,
        1.3831364e-06, 6.2482655e-07],
       [2.2202677e-07, 2.1526410e-05, 9.9995911e-01, 9.6392232e-06,
        9.3392932e-16, 4.2907350e-06, 1.6580479e-06, 5.1228256e-15,
        3.6347440e-06, 5.3800692e-13],
       [1.4923505e-06, 9.9735141e-01, 8.7150000e-04, 6.5028712e-06,
        2.3145576e-05, 3.5268899e-05, 2.4146722e-05, 8.8194455e-04,
        7.5754721e-04, 4.7003072e-05],
       [9.9957639e-01, 1.1423963e-09, 7.7460209e-05, 2.0137945e-07,
        1.4488008e-05, 1.5993562e-06, 1.8897088e-04, 1.5528082e-06,
        2.7165248e-07, 1.3898774e-04],
       [2.7245003e-06, 2.1088992e-10, 5.6563385e-06, 2.3966746e-07,
        9.9913943e-01, 2.0021175e-06, 7.7139903e-06, 9.3499912e-06,
        2.0966436e-07, 8.3266577e-04]], dtype=float32)>