In [28]:
import numpy as np
import pandas as pd
import os

In [29]:
dataset = pd.read_csv('/home/pratiyushp/Downloads/datasets/Data001.csv')
print('Loading the Datasets...')

print('dataset: %s'%(str(dataset.shape)))

Loading the Datasets...
dataset: (15, 4)


In [30]:
dataset

Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0      NaN        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6   Sri lanka  28.0  40000.0        No
7       India   NaN  60000.0        No
8       China  51.0  89000.0       Yes
9       India  44.0  78000.0       Yes
10  Sri lanka  21.0  20000.0        No
11      China  25.0  30000.0       Yes
12      India  33.0  45000.0       Yes
13      India  42.0  65000.0       Yes
14  Sri lanka  33.0  22000.0        No

In [31]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:,3].values

In [32]:
print('X: %s'%(str(X)))
print('--------------------------------------------')
print('Y: %s'%(str(Y)))

X: [['India' 34.0 92000.0]
 ['Sri lanka' 22.0 25000.0]
 ['China' 31.0 74000.0]
 ['Sri lanka' 29.0 nan]
 ['China' 55.0 98000.0]
 ['India' 24.0 30000.0]
 ['Sri lanka' 28.0 40000.0]
 ['India' nan 60000.0]
 ['China' 51.0 89000.0]
 ['India' 44.0 78000.0]
 ['Sri lanka' 21.0 20000.0]
 ['China' 25.0 30000.0]
 ['India' 33.0 45000.0]
 ['India' 42.0 65000.0]
 ['Sri lanka' 33.0 22000.0]]
--------------------------------------------
Y: ['Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes'
 'Yes' 'No']


In [33]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [34]:
print('X: %s'%(str(X)))

X: [['India' 34.0 92000.0]
 ['Sri lanka' 22.0 25000.0]
 ['China' 31.0 74000.0]
 ['Sri lanka' 29.0 54857.142857142855]
 ['China' 55.0 98000.0]
 ['India' 24.0 30000.0]
 ['Sri lanka' 28.0 40000.0]
 ['India' 33.714285714285715 60000.0]
 ['China' 51.0 89000.0]
 ['India' 44.0 78000.0]
 ['Sri lanka' 21.0 20000.0]
 ['China' 25.0 30000.0]
 ['India' 33.0 45000.0]
 ['India' 42.0 65000.0]
 ['Sri lanka' 33.0 22000.0]]


In [35]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:,0])
X[:, 0]

array([1, 2, 0, 2, 0, 1, 2, 1, 0, 1, 2, 0, 1, 1, 2], dtype=object)

**# Applying the OneHotEncoder to the first column[0]**

In [36]:
# Applying the OneHotEncoder to the first column[0]
onhotencoder = OneHotEncoder(categorical_features = [0])
X=onhotencoder.fit_transform(X).toarray()

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'categorical_features'

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

column_transformer = ColumnTransformer(
    transformers = [
        ('encoder', OneHotEncoder(), [0])
    ],
    remainder = 'passthrough'
)

X = column_transformer.fit_transform(X)

In [38]:
labelencoder_Y = LabelEncoder()
Y = labelencoder_X.fit_transform(Y)
Y

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0])

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size =0.2, random_state = 0)

In [40]:
print('X_train: %s'%(str(X_train.shape)))
print('---------------')
print('X_test: %s'%(str(X_test.shape)))
print('---------------')
print('Y_train: %s'%(str(Y_train.shape)))
print('---------------')
print('Y_test: %s'%(str(Y_test.shape)))
print('---------------')

X_train: (12, 5)
---------------
X_test: (3, 5)
---------------
Y_train: (12,)
---------------
Y_test: (3,)
---------------


In [41]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()

X_train = sc_X.fit_transform(X_train)

X_test = sc_X.transform(X_test)

In [42]:
X_train

array([[-5.77350269e-01,  1.00000000e+00, -5.77350269e-01,
         1.13100526e+00,  8.68162753e-01],
       [-5.77350269e-01, -1.00000000e+00,  1.73205081e+00,
        -7.99435932e-02, -1.31570762e+00],
       [ 1.73205081e+00, -1.00000000e+00, -5.77350269e-01,
         2.34195411e+00,  1.64811646e+00],
       [ 1.73205081e+00, -1.00000000e+00, -5.77350269e-01,
        -3.00116112e-01,  7.12172013e-01],
       [-5.77350269e-01,  1.00000000e+00, -5.77350269e-01,
         9.10832742e-01,  3.61192846e-01],
       [-5.77350269e-01, -1.00000000e+00,  1.73205081e+00,
        -1.40097871e+00, -1.39370299e+00],
       [-5.77350269e-01,  1.00000000e+00, -5.77350269e-01,
        -1.31055071e-03,  1.66204420e-01],
       [ 1.73205081e+00, -1.00000000e+00, -5.77350269e-01,
        -9.60633669e-01, -1.00372614e+00],
       [-5.77350269e-01, -1.00000000e+00,  1.73205081e+00,
        -5.20288631e-01, -3.43551036e-02],
       [-5.77350269e-01,  1.00000000e+00, -5.77350269e-01,
         3.01426663e-02

In [43]:
X_test

array([[-0.57735027, -1.        ,  1.73205081, -1.29089245, -1.19871456],
       [-0.57735027, -1.        ,  1.73205081, -0.63037489, -0.61374928],
       [ 1.73205081, -1.        , -0.57735027,  1.90160908,  1.29713729]])